Repository phovea/generator-phovea, pull requests merged in 2019-11, with the labels that each got.

#158 Added to _db_ postfix to make the docker volume ls
  generators/workspace/templates/plain/docker-backup
  generators/workspace/templates/plain/docker-backup.cmd
Labels: type: bug

#190 Configurable workspace package.json via CLI options
  generators/workspace/index.js
  generators/workspace/templates/package.tmpl.json
Labels: release: minor, type: feature

#223 Remove .travis.yml files
  .travis.yml
  generators/_init-hybrid/templates/sample_processed/.travis.yml
  generators/_init-python/templates/sample_processed/.travis.yml
  generators/_init-web/templates/sample_processed/.travis.yml
  generators/init-product/templates/plain/.travis.yml
Labels: release: major, type: technical-debt

#228 Replace deprecated `fs.exists` with recommended `fs.existsSync`
  generators/_init-python/index.js
  generators/_init-web/index.js
  generators/add-extension/index.js
  generators/init-product/index.js
  generators/init-slib/index.js
  generators/install/index.js
  generators/prepare-release/index.js
  generators/update/index.js
  generators/workspace/index.js
  utils/index.js
Labels: release: patch, type: bug

#204 Check generator version on start up
  generators/_version/index.js
  generators/add-extension/index.js
  generators/add-license-headers/index.js
  generators/app/index.js
  generators/clone-repo/index.js
  generators/clone/index.js
  generators/init-lib/index.js
  generators/install/index.js
  generators/prepare-release/index.js
  generators/resolve/index.js
  generators/setup-workspace/index.js
  generators/workspace/index.js
  package-lock.json
  package.json
  utils/index.js
Labels: release: minor, type: feature

#208 Check node version on start up functionality
  .npm-version
  .nvmrc
  generators/_check-own-version/index.js
  generators/add-extension/index.js
  generators/add-license-headers/index.js
  generators/app/index.js
  generators/check-node-version/index.js
  generators/clone-repo/index.js
  generators/clone/index.js
  generators/install/index.js
  generators/prepare-release/index.js
  generators/resolve/index.js
  generators/setup-workspace/index.js
  generators/workspace/index.js
  package-lock.json
  package.json
  test/utils-installedVersions.js
  test/utils-version.js
  utils/index.js
  utils/installedVersions.js
Labels: release: major, type: feature

#226 Switch to Jest for testing the generator
  .eslintrc
  gulpfile.js
  jest.config.js
  package-lock.json
  package.json
  test/init-lib.test.js
  test/utils-installedVersions.test.js
  test/utils-version.js
  test/utils-version.test.js
Labels: release: minor, type: refactor

#237 Add `postbuild` step to cleanup web dependencies in product build
  generators/init-product/templates/plain/build.js
Labels: release: minor, type: deployment, type: feature

#235 Pass through env variables to Docker build
  generators/init-product/templates/plain/build.js
Labels: release: minor, type: deployment, type: feature

#232 Replace `new Buffer()` with `Buffer.from()`
  generators/_init-web/templates/plain/buildInfo.js
Labels: release: patch, type: technical-debt

#225 Improve command names and add more logs
  .circleci/config.yml
  generators/_init-hybrid/templates/plain/.circleci/config.yml
  generators/_init-python/templates/plain/.circleci/config.yml
  generators/_init-web/templates/plain/.circleci/config.yml
  generators/init-product/templates/plain/.circleci/config.yml
Labels: release: patch, type: feature

#242 Release 2.0.0
  .circleci/config.yml
  .eslintrc
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/release.md
  .npm-version
  .nvmrc
  .travis.yml
  generators/_check-own-version/index.js
  generators/_init-hybrid/templates/plain/.circleci/config.yml
  generators/_init-hybrid/templates/plain/.gitlab-ci.yml
  generators/_init-hybrid/templates/sample_processed/.travis.yml
  generators/_init-python/index.js
  generators/_init-python/templates/plain/.circleci/config.yml
  generators/_init-python/templates/plain/.gitlab-ci.yml
  generators/_init-python/templates/sample_processed/.travis.yml
  generators/_init-web/index.js
  generators/_init-web/templates/package.tmpl.json
  generators/_init-web/templates/plain/.circleci/config.yml
  generators/_init-web/templates/plain/.gitlab-ci.yml
  generators/_init-web/templates/plain/buildInfo.js
  generators/_init-web/templates/sample_processed/.travis.yml
  generators/_node/index.js
  generators/add-dependency/index.js
  generators/add-extension/index.js
  generators/add-license-headers/index.js
  generators/app/index.js
  generators/check-node-version/index.js
  generators/clone-repo/index.js
  generators/clone/index.js
  generators/init-lib/index.js
  generators/init-product/index.js
  generators/init-product/templates/plain/.circleci/config.yml
  generators/init-product/templates/plain/.travis.yml
  generators/init-product/templates/plain/build.js
  generators/init-slib/index.js
  generators/install/index.js
  generators/prepare-release/index.js
  generators/resolve/index.js
  generators/setup-workspace/index.js
  generators/update/index.js
  generators/workspace/index.js
  generators/workspace/templates/package.tmpl.json
  gulpfile.js
  jest.config.js
  package-lock.json
  package.json
  test/init-lib.test.js
  test/utils-installedVersions.test.js
  test/utils-version.js
  test/utils-version.test.js
  utils/index.js
  utils/installedVersions.js
Labels: release: major

#246 Add .nvmrc + .npm-version to package.json
  package.json
Labels: priority: blocker, release: patch, type: bug

#248 Install generator ^2.0.0 for products
  generators/init-product/templates/package.tmpl.json
Labels: release: patch, type: bug

#249 Release 2.0.1
  generators/init-product/templates/package.tmpl.json
  package-lock.json
  package.json
Labels: release: patch
