Repository phovea/generator-phovea, pull requests merged in 2019-12, with the labels that each got.

#251 Fix tslint command to check only files in `src` and `tests` dire…
  generators/_init-web/templates/package.tmpl.json
Labels: release: patch, type: bug

#260 Replace `egg` with `sdist bdist_wheel` in dist:python npm command
  generators/_init-hybrid/templates/package.tmpl.json
  generators/_init-python/templates/package.tmpl.json
Labels: release: major, type: technical-debt

#266 Fix registration of yo sub-generators in setup-workspace and bui…
  generators/init-product/templates/plain/build.js
  generators/setup-workspace/index.js
Labels: release: patch, type: bug

#277 Add TypeScript compiler flags `esModuleInterop` and `allowSyntheticDefaultImports` to tsconfig.json
  generators/_init-web/templates/plain/tsconfig.json
Labels: release: minor, type: feature

#258 Change css filename from `style` to `[name]` in webpack.config.js
  generators/_init-web/templates/plain/webpack.config.js
Labels: release: patch, type: technical-debt

#256 Remove docker image from CircleCI config
  generators/init-product/templates/plain/.circleci/config.yml
Labels: release: patch, type: deployment, type: technical-debt

#253 Fix wrong file selector for typedoc command
  generators/_init-web/templates/package.tmpl.json
Labels: release: patch, type: bug

#279 Release 3.0.0
  generators/_init-hybrid/templates/package.tmpl.json
  generators/_init-python/templates/package.tmpl.json
  generators/_init-web/templates/package.tmpl.json
  generators/_init-web/templates/plain/tsconfig.json
  generators/_init-web/templates/plain/webpack.config.js
  generators/init-product/templates/plain/.circleci/config.yml
  generators/init-product/templates/plain/build.js
  generators/setup-workspace/index.js
  package-lock.json
  package.json
Labels: release: major

#280 Add blank line to setup.py to fix flake8
  generators/_init-python/templates/plain/setup.py
Labels: release: patch, type: bug

#281 Typescript 3 tslint configuration
  generators/_init-web/templates/plain/tslint.json
  generators/workspace/templates/plain/tslint.json
Labels: release: minor, type: technical-debt

#282 Remove .gitlab-ci-yml from template files
  generators/_init-hybrid/templates/plain/.gitlab-ci.yml
  generators/_init-python/templates/plain/.gitlab-ci.yml
  generators/_init-web/templates/plain/.gitlab-ci.yml
Labels: release: minor, type: technical-debt

#285 Enable Flake8 Python linting in VS Code
  generators/workspace/templates/plain/.vscode/settings.json
Labels: priority: low, release: minor, type: feature
