Repository phovea/generator-phovea, pull requests merged in 2020-03, with the labels that each got.

#341 Add `injectVersion` flag in CircleCI config
  generators/init-product/templates/plain/.circleci/config.yml
Labels: release: major, type: deployment

#333 Update to Typescript 3.8
  generators/_init-web/templates/package.tmpl.json
  generators/_init-web/templates/plain/tsconfig.json
  generators/workspace/templates/plain/tsconfig.json
Labels: priority: high, release: major, type: refactor

#344 Fix month in SNAPSHOT of version
  generators/init-product/templates/plain/build.js
Labels: release: patch, type: bug

#346 Change `buildId` to `JSON.stringify(buildId)`
  generators/_init-web/templates/plain/webpack.config.js
Labels: priority: medium, type: refactor

#339 Update dependencies
  generators/_init-hybrid/templates/package.tmpl.json
  generators/_init-python/templates/plain/requirements_dev.txt
  generators/_init-web/templates/package.tmpl.json
  generators/init-product/templates/package.tmpl.json
  generators/prepare-release/index.js
  package.json
Labels: dependencies, priority: medium, type: refactor

#348 Release 5.0.0
  README.md
  generators/_init-hybrid/templates/package.tmpl.json
  generators/_init-python/templates/plain/requirements_dev.txt
  generators/_init-web/templates/package.tmpl.json
  generators/_init-web/templates/plain/tsconfig.json
  generators/_init-web/templates/plain/tsconfig_dev.json
  generators/_init-web/templates/plain/webpack.config.js
  generators/_node/templates/README.tmpl.md
  generators/add-extension/index.js
  generators/init-product/templates/package.tmpl.json
  generators/init-product/templates/plain/.circleci/config.yml
  generators/init-product/templates/plain/build.js
  generators/prepare-release/index.js
  generators/workspace/templates/plain/tsconfig.json
  package-lock.json
  package.json
Labels: release: major

#351 Release 5.0.0
  README.md
  generators/_init-hybrid/templates/package.tmpl.json
  generators/_init-python/templates/plain/requirements_dev.txt
  generators/_init-web/templates/package.tmpl.json
  generators/_init-web/templates/plain/tsconfig.json
  generators/_init-web/templates/plain/tsconfig_dev.json
  generators/_init-web/templates/plain/webpack.config.js
  generators/_node/templates/README.tmpl.md
  generators/add-extension/index.js
  generators/init-product/templates/package.tmpl.json
  generators/init-product/templates/plain/.circleci/config.yml
  generators/init-product/templates/plain/build.js
  generators/prepare-release/index.js
  generators/workspace/templates/plain/tsconfig.json
  package-lock.json
  package.json
Labels: release: major

#328 Migrate to jest for testing
  generators/_init-hybrid/templates/package.tmpl.json
  generators/_init-web/templates/package.tmpl.json
  generators/_init-web/templates/plain/jest.config.js
  generators/_init-web/templates/plain/karma.conf.js
  generators/_init-web/templates/plain/tsd.d.ts
  generators/init-app/templates/sample_plain/tests/app.test.ts
  generators/init-lib/templates/sample_plain/tests/index.test.ts
  generators/workspace/templates/package.tmpl.json
  generators/workspace/templates/plain/jest.config.js
  generators/workspace/templates/plain/karma.conf.js
  generators/workspace/templates/plain/tsd.d.ts
Labels: release: major, type: refactor
