Repository phovea/generator-phovea, pull requests merged in 2020-05, with the labels that each got.

#373 Use four spaces for indentation
  generators/_init-python/templates/__init__.tmpl.py
  generators/_init-python/templates/plain/docs/conf.py
  generators/_init-python/templates/plain/setup.py
  generators/_node/templates/plain/.editorconfig
  generators/add-extension/templates/mapping_provider.tmpl.py
  generators/add-extension/templates/namespace.tmpl.py
  generators/add-extension/templates/tdp-sql-database-definition.tmpl.py
  generators/add-extension/templates/tdp-sql-database-extension.py
  generators/add-extension/templates/template.tmpl.py
  generators/init-service/templates/sample_pluginname_processed/server.py
  generators/init-service/templates/sample_processed/tests/test_server.py
Labels: release: patch, type: refactor

#306 Additional entries to gitignore templates
  generators/_init-hybrid/templates/_gitignore
  generators/_init-python/templates/_gitignore
  generators/_init-web/templates/_gitignore
Labels: release: minor, type: technical-debt

#313 Unified the output of `fs.extendJSONSync` and `fs.writeJSONSync`
  generators/setup-workspace/index.js
Labels: release: minor, type: bug

#335 Find max version of an array of versions
  test/utils-version.test.js
  utils/version.js
Labels: priority: blocker, priority: high, release: minor, type: bug

#229 Exclude python directory from npm release for hybrid plugins
  generators/_init-hybrid/templates/package.tmpl.json
  generators/_init-python/templates/package.tmpl.json
Labels: release: minor, type: bug

#370 Initialize plugin from the workspace
  generators/_init-hybrid/index.js
  generators/_init-python/index.js
  generators/_init-web/index.js
  generators/_node/index.js
  generators/init-app/index.js
  generators/init-product/index.js
  generators/init-service/index.js
  utils/index.js
Labels: release: minor, type: feature

#371 Add a new extension from the workspace
  generators/add-extension/index.js
Labels: release: minor, type: feature
