Repository phovea/generator-phovea, pull requests merged in 2020-04, with the labels that each got.

#336 Don't add extra underscore to plugin name in _node generator
  generators/_node/index.js
Labels: release: patch, type: bug

#303 Switch phovea.tmpl.js with phovea.tmpl.ts
  generators/_init-web/index.js
  generators/_init-web/templates/phovea.tmpl.js
  generators/_init-web/templates/phovea.tmpl.ts
  generators/_init-web/templates/processed/phovea_registry.js
  generators/add-extension/index.js
Labels: release: minor, type: technical-debt

#309 Refactor composeWith method
  generators/_init-hybrid/index.js
  generators/_init-python/index.js
  generators/_init-web/index.js
  generators/add-dependency/index.js
  generators/add-extension/index.js
  generators/add-license-headers/index.js
  generators/app/index.js
  generators/clone-repo/index.js
  generators/clone/index.js
  generators/init-product/index.js
  generators/install/index.js
  generators/prepare-release/index.js
  generators/resolve/index.js
  generators/setup-workspace/index.js
  generators/update/index.js
  generators/workspace/index.js
  utils/index.js
Labels: release: minor, type: refactor

#317 Improve generator logs
  generators/setup-workspace/index.js
  generators/workspace/index.js
Labels: release: minor, type: refactor

#359 Release 5.1.0
  generators/_init-hybrid/index.js
  generators/_init-hybrid/templates/package.tmpl.json
  generators/_init-python/index.js
  generators/_init-web/index.js
  generators/_init-web/templates/package.tmpl.json
  generators/_init-web/templates/phovea.tmpl.js
  generators/_init-web/templates/phovea.tmpl.ts
  generators/_init-web/templates/plain/jest.config.js
  generators/_init-web/templates/plain/karma.conf.js
  generators/_init-web/templates/plain/tsd.d.ts
  generators/_init-web/templates/processed/phovea_registry.js
  generators/_node/index.js
  generators/add-dependency/index.js
  generators/add-extension/index.js
  generators/add-license-headers/index.js
  generators/app/index.js
  generators/clone-repo/index.js
  generators/clone/index.js
  generators/init-app/templates/sample_plain/tests/app.test.ts
  generators/init-lib/templates/sample_plain/tests/index.test.ts
  generators/init-product/index.js
  generators/install/index.js
  generators/prepare-release/index.js
  generators/resolve/index.js
  generators/setup-workspace/index.js
  generators/update/index.js
  generators/workspace/index.js
  generators/workspace/templates/package.tmpl.json
  generators/workspace/templates/plain/jest.config.js
  generators/workspace/templates/plain/karma.conf.js
  generators/workspace/templates/plain/tsd.d.ts
  knownPhoveaPlugins.json
  package-lock.json
  package.json
  utils/index.js
Labels: release: minor

#361 Update file path in _phovea.ts_
  generators/_init-web/templates/phovea.tmpl.ts
  generators/add-extension/index.js
Labels: priority: medium, release: patch, type: bug

#364 Release 5.1.1
  generators/_init-web/templates/phovea.tmpl.ts
  generators/add-extension/index.js
  package-lock.json
  package.json
Labels: release: patch

#357 Handle version latest in package.json
  utils/version.js
Labels: release: minor, type: bug
