Repository phovea/generator-phovea, pull requests merged in 2020-08, with the labels that each got.

#409 Fix version number production build with `--injectVersion` flag
  generators/init-product/templates/plain/build.js
  generators/workspace/templates/plain_initialize_once/config/webpack.dev.js
  generators/workspace/templates/plain_initialize_once/config/webpack.prod.js
  generators/workspace/templates/plain_initialize_once/config/webpackHelper.js
Labels: priority: high, release: patch, type: bug

#408 Find intersection of github version strings
  test/utils-version.test.js
  utils/version.js
Labels: release: minor, type: bug

#412 Release 6.0.1
  generators/init-product/templates/plain/build.js
  generators/workspace/templates/plain_initialize_once/config/webpack.dev.js
  generators/workspace/templates/plain_initialize_once/config/webpack.prod.js
  generators/workspace/templates/plain_initialize_once/config/webpackHelper.js
  package-lock.json
  package.json
  test/utils-version.test.js
  utils/version.js
Labels: release: patch

#417 Update `.gitattributes` to hide compiled files from git diff
  generators/_init-web/templates/plain/.gitattributes
Labels: release: minor, type: feature

#421 Use `PHOVEA_NGINX_PORT` in nginx-default.conf
  generators/workspace/templates/plain_initialize_once/deploy/web/nginx-default.conf
Labels: priority: high, release: patch, type: bug
