Repository phovea/generator-phovea, pull requests merged in 2020-06, with the labels that each got.

#358 Update .gitattributes to create correct line endings
  .gitattributes
Labels: release: minor, type: bug

#178 Use GitHub Issue and PR templates
  generators/_init-hybrid/templates/plain/.github/ISSUE_TEMPLATE/bug-report.md
  generators/_init-hybrid/templates/plain/.github/ISSUE_TEMPLATE/feature-request.md
  generators/_init-hybrid/templates/plain/.github/PULL_REQUEST_TEMPLATE.md
  generators/_init-hybrid/templates/plain/.github/PULL_REQUEST_TEMPLATE/release.md
  generators/_init-python/templates/plain/.github/ISSUE_TEMPLATE/bug-report.md
  generators/_init-python/templates/plain/.github/ISSUE_TEMPLATE/feature-request.md
  generators/_init-python/templates/plain/.github/PULL_REQUEST_TEMPLATE.md
  generators/_init-python/templates/plain/.github/PULL_REQUEST_TEMPLATE/release.md
  generators/_init-web/templates/plain/.github/ISSUE_TEMPLATE/bug-report.md
  generators/_init-web/templates/plain/.github/ISSUE_TEMPLATE/feature-request.md
  generators/_init-web/templates/plain/.github/PULL_REQUEST_TEMPLATE.md
  generators/_init-web/templates/plain/.github/PULL_REQUEST_TEMPLATE/release.md
  generators/update/index.js
  package.json
  utils/list-plugins.js
Labels: release: minor, type: feature

#375 Remove next steps from init-lib template
  generators/init-lib/index.js
Labels: priority: medium, type: bug

#331 Add build args for injection of env vars in Dockerfile_dev
  generators/init-service/templates/sample_processed/deploy/docker-compose.partial.yml
Labels: release: minor, type: feature
