Repository phovea/generator-phovea, pull requests merged in 2020-12, with the labels that each got.

#447 Fix `copy-app-assets` npm script
  generators/init-app-slib/templates/package.tmpl.json
  generators/init-app/templates/package.tmpl.json
Labels: release: patch, type: bug

#437 Add auto-update generator
  generators/auto-update/AutoUpdateUtils.js
  generators/auto-update/GithubRestUtils.js
  generators/auto-update/index.js
  generators/auto-update/templates/update-template.js
  generators/auto-update/updates/update-6.0.0.js
  package-lock.json
  package.json
  test/AutoUpdateUtils.test.js
  test/auto-update.test.js
  test/setup-workspace.test.js
  test/test-utils/templates/repositories.csv
  utils/GeneratorUtils.js
  utils/NpmUtils.js
  utils/RepoUtils.js
  utils/SpawnUtils.js
  utils/WorkspaceUtils.js
Labels: release: minor

#441 Check if yo-rc.json exist in workspace before deleting it
  generators/setup-workspace/index.js
Labels: release: patch, type: bug

#440 Generator stylesheet refactoring changes
  generators/init-app/templates/sample_plain/src/initialize.ts
  generators/init-app/templates/sample_plain/src/scss/base/_base.scss
  generators/init-app/templates/sample_plain/src/scss/main.scss
  generators/setup-workspace/index.js
  generators/workspace/index.js
  generators/workspace/templates/package.tmpl.json
  generators/workspace/templates/plain_initialize_once/config/webpack.prod.js
  generators/workspace/templates/plain_initialize_once/config/webpackHelper.js
  test/setup-workspace.test.js
  test/workspace.test.js
  utils/GeneratorUtils.js
  utils/WorkspaceUtils.js
Labels: release: minor, type: refactor

#451 Support multiple workspace.scss (SCSS file per Webpack entry point)
  generators/workspace/templates/plain/config/webpack.dev.js
  generators/workspace/templates/plain/config/webpack.prod.js
  generators/workspace/templates/plain/config/webpackHelper.js
Labels: release: minor, type: feature

#453 Fix `copy` npm scripts for Windows
  generators/init-app-slib/templates/package.tmpl.json
  generators/init-app/templates/package.tmpl.json
  generators/init-lib-service/templates/package.tmpl.json
  generators/init-lib-slib/templates/package.tmpl.json
  generators/init-lib/templates/package.tmpl.json
Labels: release: patch, type: bug

#443 Use `rimraf` package instead of `rm -rf` in `preinstall` script
  generators/workspace/templates/package.tmpl.json
Labels: release: patch, type: bug
