Repository phovea/generator-phovea, pull requests merged in 2020-01, with the labels that each got.

#298 Update template files to Python 3.7
  generators/_init-hybrid/templates/plain/.circleci/config.yml
  generators/_init-python/templates/plain/.circleci/config.yml
  generators/_init-python/templates/plain/requirements_dev.txt
  generators/_init-python/templates/plain/setup.py
  generators/_init-python/templates/plain/tox.ini
  generators/_init-web/templates/plain/.circleci/config.yml
  generators/init-product/templates/docker-compose-patch.yaml
  generators/init-product/templates/plain/.circleci/config.yml
  generators/init-service/templates/sample_pluginname_processed/server.py
  generators/init-service/templates/sample_processed/deploy/Dockerfile
  generators/init-service/templates/sample_processed/deploy/Dockerfile_dev
  generators/workspace/templates/docker-compose-patch.yaml
  package-lock.json
Labels: release: major, type: refactor

#293 Add images formats to tsd.d.ts to allow import of gif, webp, svg
  generators/_init-web/templates/plain/tsd.d.ts
  generators/_init-web/templates/plain/webpack.config.js
  generators/workspace/templates/plain/tsd.d.ts
Labels: release: minor, type: feature

#300 Revert bundled css filename from `[name]` to `style` in webpack.config.js
  generators/_init-web/templates/plain/webpack.config.js
Labels: release: patch, type: bug
