Repository phovea/generator-phovea, pull requests merged in 2020-02, with the labels that each got.

#294 Update file selector of typedoc command in hybrid package.json template
  generators/_init-hybrid/templates/package.tmpl.json
Labels: release: patch, type: bug

#292 Remove .tar.gz generation for python dist command
  generators/_init-python/templates/package.tmpl.json
Labels: release: patch, type: bug

#329 Release 4.0.0
  .github/CODEOWNERS
  generators/_init-hybrid/templates/package.tmpl.json
  generators/_init-hybrid/templates/plain/.circleci/config.yml
  generators/_init-python/templates/package.tmpl.json
  generators/_init-python/templates/plain/.circleci/config.yml
  generators/_init-python/templates/plain/requirements_dev.txt
  generators/_init-python/templates/plain/setup.py
  generators/_init-python/templates/plain/tox.ini
  generators/_init-web/templates/plain/.circleci/config.yml
  generators/_init-web/templates/plain/tsd.d.ts
  generators/_init-web/templates/plain/webpack.config.js
  generators/init-product/templates/docker-compose-patch.yaml
  generators/init-product/templates/plain/.circleci/config.yml
  generators/init-service/templates/sample_pluginname_processed/server.py
  generators/init-service/templates/sample_processed/deploy/Dockerfile
  generators/init-service/templates/sample_processed/deploy/Dockerfile_dev
  generators/workspace/templates/docker-compose-patch.yaml
  generators/workspace/templates/plain/tsd.d.ts
  knownPhoveaPlugins.json
  package-lock.json
  package.json
Labels: release: major

#283 Use phovea.ts in `add-extension` subgenerator
  generators/add-extension/index.js
Labels: release: minor, type: technical-debt

#304 Add additional compiler options to webpack.config.json
  generators/_init-web/templates/plain/webpack.config.js
Labels: release: minor, type: technical-debt

#305 Add includes to tsconfig_dev.json
  generators/_init-web/templates/plain/tsconfig_dev.json
Labels: release: minor, type: technical-debt

#310 Remove travis and david from README.md and README.tmpl.md
  README.md
  generators/_node/templates/README.tmpl.md
Labels: release: minor, type: technical-debt

#312 Escape backslash in branch name and add repo tag in config.yml
  generators/init-product/templates/plain/.circleci/config.yml
Labels: release: minor, type: bug

#319 Show installed npm and pip dependencies during product build
  generators/init-product/templates/plain/build.js
Labels: type: deployment, type: feature
